<a href="https://colab.research.google.com/github/NoxFort1/fake-news-detector/blob/main/notebooks/01_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re

In [55]:
fake_df = pd.read_csv('Fake.csv')
true_df = pd.read_csv('True.csv')

In [56]:
fake_df.shape

(23481, 4)

In [57]:
fake_df.dtypes

title      object
text       object
subject    object
date       object
dtype: object

In [58]:
true_df.shape

(21417, 4)

In [59]:
true_df.dtypes

title      object
text       object
subject    object
date       object
dtype: object

In [60]:
fake_df['is_true'] = 0
true_df['is_true'] = 1

df = pd.concat([fake_df, true_df], ignore_index = True)
df.head()

,title,text,subject,date,is_true
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [61]:
df['subject'].unique()

array(['News', 'politics', 'Government News', 'left-news', 'US_News',
       'Middle-east', 'politicsNews', 'worldnews'], dtype=object)

In [62]:
df = df.drop(['subject', 'date'], axis=1)
df.head()

,title,text,is_true
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,0

In [63]:
def fix_split_contraction(text):
  text = re.sub(r"\b([A-Za-z]{2,})\s+n\s*t\b", r"\1n't", text, flags=re.IGNORECASE)
  text = re.sub(r"\b([A-Za-z]+)\s+(s|m|d|t|re|ve|ll)\b", r"\1'\2", text, flags=re.IGNORECASE)

  return text

In [64]:
WORD_RE = re.compile(r"(?:[A-Za-z]+|['’][A-Za-z]+)(?:['’][A-Za-z]+)*")

In [65]:
def count_words(text):
  text = ' '.join(text.split())
  text = fix_split_contraction(text)

  return len(WORD_RE.findall(text))

In [66]:
df['words_in_title'] = df['title'].apply(count_words)
df['words_in_text'] = df['text'].apply(count_words)

In [72]:
df.head()

,title,text,is_true,words_in_title,words_in_text
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,0,12,470
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,0,8,308
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",0,15,592
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",0,14,456
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,0,11,420